export const USER_FETCHED = 'auth: USER_FETCHED'
export const TOKEN_VALIDADO = 'auth: TOKEN_VALIDADO'
export const ERROR_SUBMIT = 'auth: ERROR_SUBMIT'
export const CLEAR_ERROR_SUBMIT = 'auth: CLEAR_ERROR_SUBMIT'
export const CHANGE_FIELD = 'login: CHANGE_FIELD'
